
-- Raqmiya E-Commerce Platform - Seeding Script
-- Generated by Gemini

-- Note: It is recommended to run this script on a clean database.
-- You should run your own Category and Tag insertion scripts before this one.

-- =================================================================
-- Section 1: Users
-- All users are created with the same password: Password123!
-- Salt: k9a5v2bOu8c/tG4pS+lF7w==
-- Hashed Password: J1pL9g8aJ6n5r3bF2aT/cK8vL9jH4aG/tO2bE/nC8dI=
-- =================================================================

PRINT 'Seeding Users...';
INSERT INTO [dbo].[Users] ([Username], [Email], [HashedPassword], [Salt], [Role], [CreatedAt], [IsActive])
VALUES
-- Admins
('admin', 'admin@raqmiya.com', 'J1pL9g8aJ6n5r3bF2aT/cK8vL9jH4aG/tO2bE/nC8dI=', 'k9a5v2bOu8c/tG4pS+lF7w==', 'Admin', GETUTCDATE(), 1),

-- Creators / Sellers
('art_creator', 'artist@example.com', 'J1pL9g8aJ6n5r3bF2aT/cK8vL9jH4aG/tO2bE/nC8dI=', 'k9a5v2bOu8c/tG4pS+lF7w==', 'Creator', GETUTCDATE(), 1),
('dev_creator', 'developer@example.com', 'J1pL9g8aJ6n5r3bF2aT/cK8vL9jH4aG/tO2bE/nC8dI=', 'k9a5v2bOu8c/tG4pS+lF7w==', 'Creator', GETUTCDATE(), 1),
('music_maestro', 'musician@example.com', 'J1pL9g8aJ6n5r3bF2aT/cK8vL9jH4aG/tO2bE/nC8dI=', 'k9a5v2bOu8c/tG4pS+lF7w==', 'Creator', GETUTCDATE(), 1),
('health_guru', 'health@example.com', 'J1pL9g8aJ6n5r3bF2aT/cK8vL9jH4aG/tO2bE/nC8dI=', 'k9a5v2bOu8c/tG4pS+lF7w==', 'Creator', GETUTCDATE(), 1),

-- Customers / Buyers
('john_doe', 'john.doe@example.com', 'J1pL9g8aJ6n5r3bF2aT/cK8vL9jH4aG/tO2bE/nC8dI=', 'k9a5v2bOu8c/tG4pS+lF7w==', 'Customer', GETUTCDATE(), 1),
('jane_smith', 'jane.smith@example.com', 'J1pL9g8aJ6n5r3bF2aT/cK8vL9jH4aG/tO2bE/nC8dI=', 'k9a5v2bOu8c/tG4pS+lF7w==', 'Customer', GETUTCDATE(), 1),
('tech_lover', 'techie@example.com', 'J1pL9g8aJ6n5r3bF2aT/cK8vL9jH4aG/tO2bE/nC8dI=', 'k9a5v2bOu8c/tG4pS+lF7w==', 'Customer', GETUTCDATE(), 1);


-- =================================================================
-- Section 2: Products
-- Products are generated for various categories and subcategories.
-- Creator IDs are hardcoded based on the user inserts above (2, 3, 4, 5).
-- Category IDs are assumed based on your provided script.
-- =================================================================

PRINT 'Seeding Products...';
INSERT INTO [dbo].[Products] ([Name], [Description], [Price], [Currency], [CreatorId], [IsPublic], [Permalink], [Status], [PublishedAt], [CategoryId], [CreatedAt], [UpdatedAt])
VALUES
-- Fitness & Health (CreatorId: 5, CategoryIds: 16-20)
('Ultimate Yoga Guide', 'A complete guide to mastering yoga, from beginner to advanced.', 29.99, 'USD', 5, 1, 'ultimate-yoga-guide', 'published', GETUTCDATE(), 20, GETUTCDATE(), GETUTCDATE()),
('High-Intensity Workout Plan', 'A 30-day plan to boost your fitness levels.', 19.99, 'USD', 5, 1, 'high-intensity-workout', 'published', GETUTCDATE(), 16, GETUTCDATE(), GETUTCDATE()),

-- 3D (CreatorId: 2, CategoryIds: 49-57)
('Sci-Fi Asset Pack', 'A collection of 50+ high-quality 3D models for your sci-fi scenes.', 79.99, 'USD', 2, 1, 'sci-fi-asset-pack', 'published', GETUTCDATE(), 49, GETUTCDATE(), GETUTCDATE()),
('Character Rigging in Blender', 'Learn to rig characters from scratch in Blender.', 49.99, 'USD', 2, 1, 'character-rigging-blender', 'published', GETUTCDATE(), 55, GETUTCDATE(), GETUTCDATE()),

-- Software Development (CreatorId: 3, CategoryIds: 70-74)
('Advanced C# Programming Course', 'Deep dive into advanced C# concepts and patterns.', 99.99, 'USD', 3, 1, 'advanced-csharp-course', 'published', GETUTCDATE(), 72, GETUTCDATE(), GETUTCDATE()),
('React Web Development Kit', 'Everything you need to build modern web apps with React.', 59.99, 'USD', 3, 1, 'react-web-dev-kit', 'published', GETUTCDATE(), 74, GETUTCDATE(), GETUTCDATE()),

-- Music & Sound Design (CreatorId: 4, CategoryIds: 58-61)
('Cinematic Sound Effects Library', 'A huge library of professionally designed sound effects for filmmakers.', 89.99, 'USD', 4, 1, 'cinematic-sfx-library', 'published', GETUTCDATE(), 60, GETUTCDATE(), GETUTCDATE()),
('Learn Piano: The Complete Guide', 'A comprehensive course for learning to play the piano.', 45.00, 'USD', 4, 1, 'learn-piano-complete-guide', 'published', GETUTCDATE(), 59, GETUTCDATE(), GETUTCDATE());


-- =================================================================
-- Section 3: Orders & OrderItems
-- Orders are created for customers, linking them to products.
-- User Ids (6, 7, 8), Product Ids (1-8)
-- =================================================================

PRINT 'Seeding Orders and Order Items...';
-- Order 1: John Doe buys the C# Course
INSERT INTO [dbo].[Orders] ([CustomerId], [OrderDate], [TotalAmount], [Status]) VALUES (6, GETUTCDATE(), 99.99, 'Completed');
DECLARE @OrderId1 INT = SCOPE_IDENTITY();
INSERT INTO [dbo].[OrderItems] ([OrderId], [ProductId], [Quantity], [Price]) VALUES (@OrderId1, 5, 1, 99.99);

-- Order 2: Jane Smith buys the Yoga Guide and the Workout Plan
INSERT INTO [dbo].[Orders] ([CustomerId], [OrderDate], [TotalAmount], [Status]) VALUES (7, GETUTCDATE(), 49.98, 'Completed');
DECLARE @OrderId2 INT = SCOPE_IDENTITY();
INSERT INTO [dbo].[OrderItems] ([OrderId], [ProductId], [Quantity], [Price]) VALUES (@OrderId2, 1, 1, 29.99);
INSERT INTO [dbo].[OrderItems] ([OrderId], [ProductId], [Quantity], [Price]) VALUES (@OrderId2, 2, 1, 19.99);

-- Order 3: Tech Lover buys the Sci-Fi pack and React Kit
INSERT INTO [dbo].[Orders] ([CustomerId], [OrderDate], [TotalAmount], [Status]) VALUES (8, GETUTCDATE(), 139.98, 'Completed');
DECLARE @OrderId3 INT = SCOPE_IDENTITY();
INSERT INTO [dbo].[OrderItems] ([OrderId], [ProductId], [Quantity], [Price]) VALUES (@OrderId3, 3, 1, 79.99);
INSERT INTO [dbo].[OrderItems] ([OrderId], [ProductId], [Quantity], [Price]) VALUES (@OrderId3, 6, 1, 59.99);


-- =================================================================
-- Section 4: Reviews
-- Reviews are added for purchased products.
-- =================================================================

PRINT 'Seeding Reviews...';
INSERT INTO [dbo].[Reviews] ([ProductId], [UserId], [Rating], [Comment], [CreatedAt], [IsApproved])
VALUES
(5, 6, 5, 'Excellent course! Very detailed and easy to follow.', GETUTCDATE(), 1),
(1, 7, 5, 'Loved this yoga guide. The illustrations are beautiful.', GETUTCDATE(), 1),
(2, 7, 4, 'Great workout plan, very challenging but effective.', GETUTCDATE(), 1),
(3, 8, 5, 'These 3D assets are amazing quality. Saved me so much time!', GETUTCDATE(), 1),
(6, 8, 4, 'Good starting point for React development.', GETUTCDATE(), 1);


-- =================================================================
-- Section 5: WishlistItems
-- Items are added to customer wishlists.
-- =================================================================

PRINT 'Seeding Wishlist Items...';
INSERT INTO [dbo].[WishlistItems] ([UserId], [ProductId], [AddedAt])
VALUES
-- John Doe's Wishlist
(6, 3), -- Sci-Fi Asset Pack
(6, 7), -- Cinematic Sound Effects

-- Jane Smith's Wishlist
(7, 5), -- Advanced C# Course
(7, 8), -- Learn Piano Guide

-- Tech Lover's Wishlist
(8, 1), -- Ultimate Yoga Guide
(8, 4); -- Character Rigging in Blender

PRINT 'Database seeding completed successfully.';
